name: Fetch GitHub App Installation Access Token
description: "Fetches an installation access token for a GitHub App, that can be used to clone private repositories."
author: "Lobaro GmbH"
inputs:
  app-id:
    description: GitHub App ID
    required: true
  private-key:
    description: Private key for the GitHub App
    required: true
  repo:
    description: Override GITHUB_REPOSITORY when creating the installation ID
    required: false
    default: ${{ github.repository }}
outputs:
  token:
    description: Installation access token for the GitHub App

runs:
  using: node24
  main: dist/index.js
